const answers = [
    "Kesinlikle!",
    "Bunu yapmamalısın.",
    "Bence bu iyi bir fikir.",
    "Bu yol doğru değil.",
    "Hemen harekete geç.",
    "Biraz daha düşünmelisin.",
    "Bu konuda haklısın.",
    "Bu durum biraz karmaşık.",
    "Buna katılıyorum.",
    "Başka bir yol denemelisin.",
    "Bunun senin için faydalı olacağını düşünüyorum.",
    "Bu konu hakkında daha fazla bilgiye ihtiyacın var.",
    "Bu doğru bir adım.",
    "Risk almak istemiyorum.",
    "Bu doğru bir yaklaşım.",
    "Acele etmemek daha iyi.",
    "Bunu yapmalısın.",
    "Durumu daha iyi anlaman lazım.",
    "Kendine güvenebilirsin.",
    "Bu aşamada daha fazla araştırmalısın.",
    "Bunu denemek iyi bir fikir.",
    "Bunun için zamanın yok.",
    "Kesinlikle deneyebilirsin.",
    "Bunun sonuçları olabilir.",
    "Bence ilerlemelisin.",
    "Başkalarını dinlemelisin.",
    "Senin için en iyisi bu.",
    "Başka seçenekler de var.",
    "Bu senin için iyi bir fırsat.",
    "Bu sefer daha temkinli olmalısın.",
    "Bunu yapabilirsin.",
    "Düşünmeden hareket etme.",
    "Sonuçları merak ediyorum.",
    "Başka bir yol daha iyi görünüyor.",
    "Bu senin için doğru seçim.",
    "Bu planı gözden geçirmen gerekiyor.",
    "Bunun üzerine daha fazla düşünmelisin.",
    "Belirsizlikte hareket etmek risklidir.",
    "Bu senin için faydalı olabilir.",
    "Bu konuda bir uzmandan yardım almalısın.",
    "Bu yönde ilerlemek mantıklı.",
    "Bir süre beklemek daha iyi olabilir.",
    "Kendini ifade etmelisin.",
    "Buna dikkat etmelisin.",
    "Her şey yolunda görünüyor.",
    "Yeni bir başlangıç yapmalısın.",
    "Geçmişi geride bırak.",
    "Zamanlaman önemli.",
    "Bir adım geri çekilmekte fayda var.",
    "Bu fırsatı kaçırmamalısın.",
    "Eyleme geçme zamanı geldi.",
    "Kendi yolunu çizmelisin.",
    "Olumsuzlukları bir kenara bırak.",
    "Denemekten vazgeçme.",
    "Bunu gerçekleştirmek için plan yapmalısın.",
    "İç sesini dinle.",
    "Sorunları çözmek için yaratıcı olmalısın.",
    "Güçlü kalmaya çalış.",
    "Bu süreçte sabırlı olmalısın.",
    "Her durumda pozitif kalmaya çalış."
  ];
  export default answers;  